let a, b, c;
a = 5;
b = 2;
c = a + b;
document.getElementById("demo").innerHTML = "Summa on " + c;
c = a - b;
document.getElementById("demo1").innerHTML = "Erotus on " + c;
c = a * b;
document.getElementById("demo2").innerHTML = "Tulo on " + c;
c = a / b;
document.getElementById("demo3").innerHTML = "Jako on " + c;
c = a % b;
document.getElementById("demo4").innerHTML = "Jakokäännös on " + c;
a--;
document.getElementById("demo5").innerHTML = "a:n arvo on nyt " + a;
b++;
document.getElementById("demo6").innerHTML = "b:n arvo on nyt " + b;
let d;
d = a ** b;
